// This file is generated by Slice Machine. Update with care!

import About from './About';
import Gallery from './Gallery';

export {
	About,
	Gallery,
};

export const components = {
	about: About,
	gallery: Gallery,
};
