// This file is generated by Slice Machine. Update with care!

import Gallery from './Gallery';
import SimpleText from './SimpleText';

export {
	Gallery,
	SimpleText,
};

export const components = {
	gallery: Gallery,
	simple_text: SimpleText,
};
